export const forumConstants = {
  CHANGE_SELECTED_SORT: "CHANGE_SELECTED_SORT",
  CHANGE_DISPLAY_POSTS: "CHANGE_DISPLAY_POSTS",
  HANDLE_UPVOTE: "HANDLE_UPVOTE",
  HANDLE_DOWNVOTE: "HANDLE_DOWNVOTE",
  SELECT_POST: "SELECT_POST",
  HANDLE_BOOKMARK: "HANDLE_BOOKMARK",
};
